name: Common CI

on:
  workflow_call:
    inputs:
      skip-tests:
        required: false
        type: boolean
        default: false

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0
      - name: Build
        run: zig build
      - name: Test
        if: ${{ !inputs.skip-tests }}
        run: zig build test
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: zig-out
          key: ${{ runner.os }}-zig-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-zig-
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0
      - name: Format code
        run: zig fmt src/generated/version.zig || true
      - name: Lint code
        run: zig fmt --check src/ || echo "Formatting issues found"
