name: CI

on:
  push:
    branches: [main, develop, 'release/*', 'hotfix/*']
  pull_request:
    branches: [main, develop, 'release/*', 'hotfix/*']

jobs:
  common:
    uses: ./.github/workflows/ci-common.yml
    with:
      skip-tests: false
