name: Develop Branch Workflow

on:
  push:
    branches:
      - develop

jobs:
  ci:
    uses: ./.github/workflows/ci-common.yml
    with:
      skip-tests: false
    secrets: inherit

  # Optional: You can include additional version check steps here.
  version-check:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Version Check — Manual Bump if Needed
        shell: pwsh
        run: |
          Write-Host "Version bumping is managed manually via the promote workflow."
