name: Feature Branch Workflow

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0
      
      - name: Build
        run: zig build
      
      - name: Test
        run: zig build test
      
      - name: Validate branch name
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          if [[ ! $BRANCH_NAME =~ ^(feature|bugfix)/[a-z0-9_-]+$ ]]; then
            echo "Branch naming should follow feature/feature-name or bugfix/issue-name convention"
            exit 1
          fi
