name: Hotfix Process

on:
  workflow_dispatch:
    inputs:
      baseBranch:
        description: 'Base branch for hotfix (usually main)'
        required: true
        default: 'main'
      hotfixName:
        description: 'Hotfix name (e.g., fix-critical-bug)'
        required: true
      bumpType:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor

jobs:
  create-hotfix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.baseBranch }}
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
      
      - name: Create hotfix branch
        run: |
          git checkout -b hotfix/${{ github.event.inputs.hotfixName }}
          git push -u origin hotfix/${{ github.event.inputs.hotfixName }}
      
      - name: Create PR for tracking
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: hotfix/${{ github.event.inputs.hotfixName }}
          base: ${{ github.event.inputs.baseBranch }}
          title: 'Hotfix: ${{ github.event.inputs.hotfixName }}'
          body: |
            ## Hotfix PR
            
            This PR was automatically created to track the hotfix process for: 
            `${{ github.event.inputs.hotfixName }}`
            
            ### Workflow:
            1. Make necessary changes in this branch
            2. Test thoroughly
            3. When ready, use the "Release Hotfix" workflow to:
               - Bump version
               - Create release
               - Auto-merge back to develop
          draft: false
          labels: hotfix
