name: Release

permissions:
  contents: write
  pull-requests: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  ci:
    uses: ./.github/workflows/ci-common.yml
    with:
      skip-tests: false
    secrets: inherit

  create-release:
    needs: ci
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Extract Version from Tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Create Final Release on GitHub
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: "Zeta Release ${{ github.ref_name }}"
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

  build-and-upload:
    needs: create-release
    uses: ./.github/workflows/build-and-upload-release.yml
    with:
      upload_url: ${{ needs.create-release.outputs.upload_url }}
      ref_name: ${{ github.ref_name }}
    secrets: inherit
